networks:
  locally:

services:
  rest:
    build:
      context: ../aspnet
      dockerfile: ../.docker/machine.dockerfile
    depends_on:
      - data
    env_file:
      - ../.docker/docker.env
    environment:
      ConnectionStrings__pgsql: "Host=data;Database=MediaData;Username=postgres;Password=MediaData@2020;"
      ConnectionStrings__zipkin: "http://trace:9411/"
    networks:
      - locally
    ports:
      - 8003:80

  data:
    environment:
      POSTGRES_PASSWORD: MediaData@2020
    image: postgres:12
    networks:
      - locally

  trace:
    image: openzipkin/zipkin-slim
    networks:
      - locally
    ports:
      - 9003:9411

version: "3.8"
